apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Use a specific version instead 'main' if you want to install a specific version
  #- https://raw.githubusercontent.com/external-secrets/external-secrets/main/deploy/crds/bundle.yaml
  - https://raw.githubusercontent.com/external-secrets/external-secrets/v0.20.4/deploy/crds/bundle.yaml
